### ISSUE TITLE
[proxy] broken in production with latest release

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/market-api#18]
@rojosnow - appears the latest release may have broken some of the functionality in the production dApp.

![image](https://user-images.githubusercontent.com/15096737/42693409-41621538-866c-11e8-8677-277c717e14df.png)

Can you research and report back ASAP

**Comment by rojosnow** [comment]
Resolved. Enabling cors in serverless is easy...but more specificity is needed to allow preflight headers for a `XMLHttpRequest`. Only the "safe" headers are enabled by default.
