### ISSUE TITLE
[dApp] Create a proxy to fetch exchangeInfo from Binance API

### ISSUE THREAD

**Issue by eswarasai** [MARKETProtocol/market-api#2]
### User Story
Fetch exchangeInfo from Binance API

### Why Is this Needed?
Binance API doesn't allow CORS. Build a GET API to proxy the request of Binance API

Sample code -- https://gist.github.com/bakaoh/b11ad2976e7f0faf92e9d0b4d294990e

**Comment by rojosnow** [comment]
API endpoint clarification:

- Create a proxy endpoint allowing https://api.marketprotocol.io/proxy/binance/*
- Accepts a variable number of path parameters
- Proxy the API calls directly from https://api.binance.com/*
- Example: to fetch the ticker price, call: https://api.marketprotocol.io/proxy/binance/api/v3/ticker/price

@eswarasai Let me know if you need anything else.

**Comment by eswarasai** [comment]
@rojosnow -- That seems fine to me 👍

**Comment by rojosnow** [comment]
@eswarasai This is done. I had stubbed the proxy to handle a variety of cases. If you need to send query parameters, it supports that too. https://api.marketprotocol.io/proxy/binance/api/v3/ticker/price. It should work as expected. The OPTIONS request headers are also as expected.

**Comment by rojosnow** [comment]
Committed to `develop` branch.
