### ISSUE TITLE
BUG: 502 Status Code despite successful looking response 

### ISSUE THREAD

**Issue by dmvt** [MARKETProtocol/market-api#32]
This is an intermittent issue. When hitting the production API with the dApp the ticker price endpoint (https://api.marketprotocol.io/proxy/binance/api/v3/ticker/price) returns a 502 error despite providing a valid looking JSON response.

![screenshot from 2018-08-03 13-45-01](https://user-images.githubusercontent.com/1116695/43657647-70304614-9724-11e8-9d7b-49ff50f28e52.png)
![screenshot from 2018-08-03 13-45-25](https://user-images.githubusercontent.com/1116695/43657655-7655eb98-9724-11e8-9555-6600fb84c7c8.png)
![screenshot from 2018-08-03 13-47-34](https://user-images.githubusercontent.com/1116695/43657666-7bc0e092-9724-11e8-899e-1eb278302463.png)
![screenshot from 2018-08-03 13-47-53](https://user-images.githubusercontent.com/1116695/43657671-7e14965e-9724-11e8-8651-fa56438ed782.png)

### Description
[comment]: # (Feature, Enhancement, or Bug? i.e Type: Bug)
*Type*: Bug

### Current Behavior
[comment]: # (Describe what actually happened.)
Sometimes a 502 error response code is returned.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
A 200 success response code to be returned.

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
I have been unable to consistently reproduce the error, but this is the second time in 24 hours I've experienced it.

**Comment by rojosnow** [comment]
Ref: #37 should fix this issue.
