### ISSUE TITLE
[market.js] Refactor to use the latest version of MARKET.js

### ISSUE THREAD

**Issue by rojosnow** [MARKETProtocol/market-api#33]
@rojosnow commented on [Mon Jul 30 2018](https://github.com/MARKETProtocol/MARKET.js/issues/117)

### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a dev, I need to refactor market-api so that is works with the latest refactor of market.js.

### Why Is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:
Get market-api to work with the latest version of MARKET.js

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Enhancement

### Solution
[comment]: # (Provide a summary of the solution and a task list on what needs to be fixed.)
*Summary*:
Implement the latest version of MARKET.js in market-api.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
market-api works with the `^0.3.0` version of MARKET.js.

---

@perfectmak commented on [Fri Aug 10 2018](https://github.com/MARKETProtocol/MARKET.js/issues/117#issuecomment-412151840)

@rojosnow shouldn't this be in the [market-api ](https://github.com/MARKETProtocol/market-api) repository or maybe I'm clear of the description?

**Comment by pelsasser** [comment]
@rojosnow - do you have a time frame for completion on this? I am happy to help out to get it done as @nitinrgupta and @travisdmathis are butting up against not having data for the new UI.

**Comment by rojosnow** [comment]
@pelsasser I finished the factor yesterday and pushed it only to dev. Ex: https://lb00q1lyn8.execute-api.us-east-1.amazonaws.com/dev/orders/0x83bb1ea3fe889d88451fbb3178f04d4cb9830f61. I wanted to do some more testing before making it available to the dapp. Remember all of the endpoints were touched so I don't want to break the dapp again. ;) @nitinrgupta @travisdmathis Please verify the orders are correct.
