### ISSUE TITLE
Market API endpoints should handle conversion of big numbers for storage

### ISSUE THREAD

**Issue by travisdmathis** [MARKETProtocol/market-api#43]
##### User Story

- As an <audience/user>:  
- I want to <action/task>: 
- so that <outcome/goal/benefit>: 

#### Type

- [ ] Feature
- [x] Enhancement
- [ ] Bug

#### Description

Market Contract API endpoints should handle the conversion of big numbers to the value needed for storage in string format. 

#### Solution

The following data points should be updated to receive a BigNumber and convert it to whatever format you need for storage in the postgres database.

- [x] Update the db schema to support collateralPoolBalance (string), bigint still covers all of the other fields
- [x] Add is_whitelisted, is_settled, expiration_timestamp indexes
- [ ] Modify the db tables: local, dev, test, prod
- [x] Modify the contract schema, define a NumberString to handle collateralPoolBalance
- [x] Modify the POST/PUT requests to munge event data into the correct types
- [x] Modify the GET response to return just strings and booleans, the coversion to numbers will be handled in the app
- [x] Update constants
- [x] Update tests where appropriate

#### Definition of Done

The following end points handle big numbers
- collateralPoolBalance
- expirationTimestamp
- lastQueriedPrice
- lastTradePrice
- priceCap
- priceDecimalPlaces
- priceFloor
- qtyMultiplier

#### Attach files or screenshots if it's helpful for this issue.

**Comment by rojosnow** [comment]
@travisdmathis I'm assuming you want the data back exactly the way you gave it to me...or do you want me to return it with the decimal places applied? Either way is fine with me.

**Comment by travisdmathis** [comment]
@rojosnow i'd say return it to us the same way its stored, don't apply any conversions
